// Generates index.html and the journey compositions from edit.json and the recorded takes.
//
//   node tools/build.mjs
//
// - Journey compositions (compositions/j-*.html): the real-app take plays full frame; the camera starts
//   wide on each page (full app chrome), then punches in on the element each step used, framed with
//   margin (never tighter than 1.6x). Camera targets come from assets/ui/take-*.json (the boxes the
//   recorder logged), so re-recording re-aims the camera. Titles and short summaries sit in a band
//   at the bottom; the only composited UI element is the labelled synthetic Outlook stand-in.
// - Higgsfield slots: when assets/hf/<name>.mp4 exists it plays; otherwise the slot's HyperFrames
//   stand-in composition plays in the same window.
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const edit = JSON.parse(readFileSync(join(root, "edit.json"), "utf8"));
const take = (n) => JSON.parse(readFileSync(join(root, "assets", "ui", `take-${n}.json`), "utf8"));
const W = 1920, H = 1080, MAXZ = 1.6;
const WIDE = /^(nav-|open-|prep-|tile-|tab-|calendar-)/;
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;");

function camera(box) {
  const fw = Math.min(W, Math.max(box.w * 1.5 + 260, ((box.h * 1.5 + 220) * 16) / 9, W / MAXZ));
  const z = W / fw;
  const cx = box.x + box.w / 2, cy = box.y + box.h / 2;
  const x = Math.min(0, Math.max(W - W * z, W / 2 - cx * z));
  const y = Math.min(0, Math.max(H - H * z, H / 2 - cy * z));
  return { z: +z.toFixed(3), x: Math.round(x), y: Math.round(y) };
}

const FONTS = `@font-face { font-family: Karma; src: url("assets/fonts/Karma-Medium.ttf") format("truetype"); font-weight: 500; }
      @font-face { font-family: Geist; src: url("assets/fonts/Geist-Variable.woff2") format("woff2"); font-weight: 100 900; }`;

function journey(seg) {
  const t = take(seg.take);
  const id = seg.id;
  const dur = +(seg.end - seg.start).toFixed(3);
  const rate = +((seg.to - seg.from) / dur).toFixed(4);
  const ft = (tt) => +((tt - seg.from) / rate).toFixed(2); // composition-local time
  const tweens = [`tl.set("#${id}-cam", { scale: 1, x: 0, y: 0, transformOrigin: "0 0" }, 0);`];
  for (const s of t.steps) {
    if (s.actual < seg.from - 0.05 || s.actual > seg.to) continue;
    const at = ft(s.actual);
    if (WIDE.test(s.name) || !s.box) tweens.push(`tl.to("#${id}-cam", { scale: 1, x: 0, y: 0, duration: 0.7, ease: "power3.inOut", overwrite: "auto" }, ${Math.max(0, at + 0.15)}); // ${s.name}`);
    else {
      const c = camera(s.box);
      tweens.push(`tl.to("#${id}-cam", { scale: ${c.z}, x: ${c.x}, y: ${c.y}, duration: 0.8, ease: "power3.inOut", overwrite: "auto" }, ${Math.max(0, at - 0.45)}); // ${s.name}`);
    }
  }
  const sums = (seg.summaries ?? []).map((m, i) => {
    const step = t.steps.find((s) => s.name === m.step);
    const at = Math.max(0.4, step ? ft(step.actual) + (m.offset ?? 0) : m.at ?? 0);
    const next = seg.summaries[i + 1];
    const nstep = next && t.steps.find((s) => s.name === next.step);
    const until = next ? Math.max(at + 1.2, nstep ? ft(nstep.actual) + (next.offset ?? 0) : next.at) : dur;
    return { text: m.text, at: +at.toFixed(2), until: +until.toFixed(2) };
  });
  const standin = seg.standin
    ? `<div id="${id}-standin" style="position:absolute;left:${seg.standin.x}px;top:${seg.standin.y}px;width:${seg.standin.w}px;padding:10px 16px;border-radius:8px;background:#faebec;border-left:5px solid #c5050c;box-shadow:0 6px 18px rgba(26,13,11,.18);font:500 19px/1.35 Geist,system-ui,sans-serif;color:#29231f"><span style="color:#9b0000">${esc(seg.standin.from)}</span> · ${esc(seg.standin.text)}<span style="float:right;font-size:14px;color:#5c0b10;background:#fff;border:1px solid #f6d9da;border-radius:5px;padding:1px 7px">${esc(seg.standin.tag)}</span></div>`
    : "";
  const sumHtml = sums.map((s, i) => `<div class="j-sum" id="${id}-s${i}">${esc(s.text)}</div>`).join("\n        ");
  const sumTl = sums
    .map((s, i) => `tl.fromTo("#${id}-s${i}", { y: 18, opacity: 0 }, { y: 0, opacity: 1, duration: 0.45, ease: "expo.out" }, ${s.at});${i < sums.length - 1 ? `\n        tl.to("#${id}-s${i}", { opacity: 0, duration: 0.2 }, ${Math.max(s.at + 0.6, s.until - 0.2)});` : ""}`)
    .join("\n        ");
  const html = `<!doctype html>
<!-- Generated by tools/build.mjs from edit.json and assets/ui/take-${seg.take}.json. Do not edit by hand. -->
<html><head><meta charset="UTF-8" /></head><body>
  <template>
    <style>
      ${FONTS}
      #${id}-root { position: absolute; inset: 0; overflow: hidden; background: #1a0d0b; }
      #${id}-cam { position: absolute; left: 0; top: 0; width: ${W}px; height: ${H}px; }
      #${id}-cam video { position: absolute; inset: 0; width: ${W}px; height: ${H}px; object-fit: cover; }
      #${id}-band { position: absolute; left: 0; right: 0; bottom: 0; height: 250px; background: linear-gradient(180deg, rgba(26, 13, 11, 0), rgba(26, 13, 11, 0.78) 45%, rgba(26, 13, 11, 0.9)); }
      #${id}-title { position: absolute; left: 96px; bottom: 104px; font-family: Karma, Georgia, serif; font-weight: 500; font-size: 58px; line-height: 1.05; color: #fff; }
      #${id}-root .j-sum { position: absolute; left: 98px; bottom: 50px; font-family: Geist, system-ui, sans-serif; font-weight: 500; font-size: 34px; color: #f7c440; }
    </style>
    <div id="${id}-root" data-composition-id="${id}" data-width="${W}" data-height="${H}">
      <div id="${id}-cam">
        <video id="${id}-video" src="assets/ui/take-${seg.take}.mp4" data-start="0" data-duration="${dur}" data-media-start="${seg.from}" data-playback-rate="${rate}" muted playsinline data-layout-allow-overflow></video>
        ${standin}
      </div>
      <div id="${id}-band"></div>
      <div id="${id}-title">${esc(seg.title)}</div>
        ${sumHtml}
    </div>
    <script>
      (() => {
        const tl = gsap.timeline({ paused: true });
        ${tweens.join("\n        ")}
        tl.fromTo("#${id}-title", { y: 24, opacity: 0 }, { y: 0, opacity: 1, duration: 0.6, ease: "expo.out" }, 0.1);
        ${seg.standin ? `tl.fromTo("#${id}-standin", { y: -14, opacity: 0 }, { y: 0, opacity: 1, duration: 0.5, ease: "back.out(2)" }, ${seg.standin.at ?? 0.3});` : ""}
        ${sumTl}
        window.__timelines["${id}"] = tl;
      })();
    </script>
  </template>
</body></html>
`;
  writeFileSync(join(root, "compositions", `${id}.html`), html);
  return { id, dur, rate };
}

const MASK = ' style="-webkit-mask-image: linear-gradient(90deg, transparent 48%, #000 60%); mask-image: linear-gradient(90deg, transparent 48%, #000 60%)"';
const host = (id, start, dur, track, extra = "") => `<div id="${id}-host" class="scene" data-composition-id="${id}" data-composition-src="compositions/${id}.html" data-start="${start}" data-duration="${dur}" data-track-index="${track}" data-width="${W}" data-height="${H}"${extra}></div>`;
const rows = [];
const report = [];
for (const s of edit.timeline) {
  const dur = +(s.end - s.start).toFixed(3);
  if (s.kind === "footage") {
    rows.push(`<video id="${s.id}" class="slot clip" src="${s.file}" data-start="${s.start}" data-duration="${dur}" data-track-index="0" muted playsinline></video>`);
    rows.push(`<audio id="${s.id}-audio" src="${s.file}" data-start="${s.start}" data-duration="${dur}" data-track-index="20" data-volume="1"></audio>`);
  } else if (s.kind === "hf") {
    const have = existsSync(join(root, s.file));
    const mask = s.mask === "right" ? MASK : "";
    if (have) rows.push(`<video id="${s.id}" class="slot clip" src="${s.file}" data-start="${s.start}" data-duration="${dur}" data-track-index="2" muted playsinline${mask}></video>`);
    else rows.push(host(s.standin, s.start, dur, 2, mask));
    report.push(`${s.file}: ${have ? "clip" : "stand-in " + s.standin} ${s.start}-${s.end}s (${dur}s)`);
  } else if (s.kind === "journey") {
    const j = journey(s);
    rows.push(host(j.id, s.start, dur, 2));
    report.push(`${j.id}: take ${s.take} ${s.from}-${s.to}s at ${j.rate}x → film ${s.start}-${s.end}s`);
  } else if (s.kind === "comp") rows.push(host(s.id, s.start, dur, s.track ?? 3));
}
const sfxLen = (f) => Number(execFileSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", join(root, "assets/sfx", `${f}.mp3`)], { encoding: "utf8" }).trim());
const sfx = edit.sfx.map((x, i) => `<audio id="sfx-${i}-${x.file.replace(/\W+/g, "")}" src="assets/sfx/${x.file}.mp3" data-start="${x.at}" data-duration="${Math.min(x.dur ?? 3, sfxLen(x.file)).toFixed(2)}" data-track-index="${30 + (i % 6)}" data-volume="${x.vol ?? 0.35}"></audio>`);
const html = `<!doctype html>
<!-- Generated by tools/build.mjs from edit.json (built to PRODUCTION-SCRIPT.md). Edit edit.json, then run: node tools/build.mjs -->
<html lang="en" data-resolution="landscape">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>My Magic UW: submission film</title>
    <script src="node_modules/gsap/dist/gsap.min.js"></script>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { margin: 0; width: 1920px; height: 1080px; overflow: hidden; background: #1a0d0b; }
      #root { position: relative; width: 100%; height: 100%; overflow: hidden; }
      .slot { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; }
      .scene { position: absolute; inset: 0; }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-duration="${edit.duration}" data-width="1920" data-height="1080">
      ${rows.join("\n      ")}
      ${host("captions", 0, edit.duration, 9, ' data-track-kind="captions"')}
      <audio id="narration" src="assets/narration.wav" data-start="0" data-duration="${edit.duration}" data-track-index="22" data-volume="1"></audio>
      <audio id="dialogue-guide" src="assets/dialogue-guide.wav" data-start="0" data-duration="${edit.duration}" data-track-index="23" data-volume="0.9"></audio>
      <audio id="music" src="assets/music-bed.wav" data-start="0" data-duration="${edit.duration}" data-track-index="24" data-volume="0.35"></audio>
      ${sfx.join("\n      ")}
    </div>
    <script>
      window.__timelines["main"] = gsap.timeline({ paused: true });
    </script>
  </body>
</html>
`;
writeFileSync(join(root, "index.html"), html);
// First frame of take A as the spell stand-in's target window.
mkdirSync(join(root, "assets", "ui"), { recursive: true });
execFileSync("ffmpeg", ["-loglevel", "error", "-y", "-ss", "0.3", "-i", join(root, "assets/ui/take-a.mp4"), "-frames:v", "1", "-vf", "scale=1920:1080", join(root, "assets/ui/home-first.png")]);
execFileSync("ffmpeg", ["-loglevel", "error", "-y", "-ss", "7.6", "-i", join(root, "assets/ui/take-b.mp4"), "-frames:v", "1", "-vf", "scale=1920:1080", join(root, "assets/ui/course-first.png")]);
console.log(report.join("\n"));
