// Silent, loop-friendly clips of the film's scenes for the marketing site.
//
//   node tools/loops.mjs <site loops folder> [--no-render]
//
// 1. Writes loops.html: index.html without audio, captions, or the skit/presenter footage.
// 2. Renders it once (local, telemetry off) to out/loops-source.mp4.
// 3. Cuts each slot, crossfading its tail into its head so the last frame flows into the first,
//    at 1280x720: <slot>.webm (VP9), <slot>.mp4 (H.264, +faststart), <slot>-poster.jpg (first frame).
//    Every file must stay under 1.5 MB; CRF rises until it does.
// Slot names follow apps/web/assets/loops/README.md on feat/site-update.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, statSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const dest = resolve(process.argv[2] ?? join(root, "out", "loops"));
mkdirSync(dest, { recursive: true });
const source = join(root, "out", "loops-source.mp4");
const LIMIT = 1.5 * 1024 * 1024;
const FADE = 0.6;

// film-time windows; first frame of the loop = start + FADE. crop: [x, y, w, h] of the 1920x1080 frame.
const SLOTS = [
  { slot: "spell", start: 29.4, end: 36.2 },
  { slot: "agenda", start: 38.9, end: 46.0 },
  { slot: "item-space", start: 46.4, end: 53.0 },
  { slot: "quiz", start: 56.3, end: 62.0 },
  { slot: "analytics", start: 62.2, end: 70.4 },
  { slot: "guard", start: 71.4, end: 79.0 },
  { slot: "agent-ring", start: 94.6, end: 101.4, crop: [758, 190, 1164, 655] }, // x, y, w, h
];

if (!process.argv.includes("--no-render")) {
  let html = readFileSync(join(root, "index.html"), "utf8");
  html = html.replace(/\s*<audio [^>]*><\/audio>/g, "");
  html = html.replace(/<video id="(skit|presenters)" /g, '<video id="$1" data-hidden ');
  html = html.replace('<div id="captions-host" ', '<div id="captions-host" data-hidden ');
  html = html.replace('<div id="ground" class="clip" data-start="20" data-duration="70"', '<div id="ground" class="clip" data-start="0" data-duration="120"');
  writeFileSync(join(root, "out", "loops.html"), html.replace("<title>My Magic UW: submission film</title>", "<title>My Magic UW: silent loops (generated by tools/loops.mjs)</title>"));
  execFileSync("npx", ["--yes", "hyperframes@0.8.79", "render", "-c", "out/loops.html", "--workers", "4", "-o", "out/loops-source.mp4"], { cwd: root, stdio: "inherit", shell: true, env: { ...process.env, HYPERFRAMES_NO_TELEMETRY: "1", DO_NOT_TRACK: "1" } });
}

const ff = (args) => execFileSync("ffmpeg", ["-loglevel", "error", "-y", ...args], { stdio: "inherit" });
const report = [];
for (const s of SLOTS) {
  const d = +(s.end - s.start).toFixed(3);
  const crop = s.crop ? `crop=${s.crop[2]}:${s.crop[3]}:${s.crop[0]}:${s.crop[1]},` : "";
  const graph = `[0:v]trim=start=${s.start}:duration=${d},setpts=PTS-STARTPTS,${crop}scale=1280:720:flags=lanczos,fps=30,format=yuv420p,split[a][b];` + `[b]trim=0:${FADE},setpts=PTS-STARTPTS[head];[a]trim=${FADE}:${d},setpts=PTS-STARTPTS[body];` + `[body][head]xfade=transition=fade:duration=${FADE}:offset=${(d - 2 * FADE).toFixed(3)}[out]`;
  const enc = (file, codecArgs) => ff(["-i", source, "-filter_complex", graph, "-map", "[out]", "-an", ...codecArgs, join(dest, file)]);
  for (let crf = 26; crf <= 40; crf += 3) {
    enc(`${s.slot}.mp4`, ["-c:v", "libx264", "-preset", "slow", "-crf", String(crf), "-movflags", "+faststart", "-pix_fmt", "yuv420p"]);
    if (statSync(join(dest, `${s.slot}.mp4`)).size < LIMIT) break;
  }
  for (let crf = 36; crf <= 50; crf += 4) {
    enc(`${s.slot}.webm`, ["-c:v", "libvpx-vp9", "-b:v", "0", "-crf", String(crf), "-row-mt", "1", "-deadline", "good", "-cpu-used", "2"]);
    if (statSync(join(dest, `${s.slot}.webm`)).size < LIMIT) break;
  }
  ff(["-i", join(dest, `${s.slot}.mp4`), "-frames:v", "1", "-q:v", "3", join(dest, `${s.slot}-poster.jpg`)]);
  const kb = (f) => Math.round(statSync(join(dest, f)).size / 1024);
  report.push(`${s.slot}: ${(d - FADE).toFixed(1)} s · mp4 ${kb(`${s.slot}.mp4`)} KB · webm ${kb(`${s.slot}.webm`)} KB · poster ${kb(`${s.slot}-poster.jpg`)} KB`);
}
console.log(report.join("\n"));
