// Generates the Whiz overlays (compositions/w-*.html): the wizard mark flies over the real-app
// footage on a keyframed path, waves, taps a target with his staff (sparkle "poof"), or celebrates.
// Transparent background; they sit on track 5 above the journeys. Coordinates are film pixels
// (1920x1080) with the journey camera wide at the moments Whiz points at something.
//
//   node tools/whiz.mjs
import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const STAR = `<path d="M0 -10 L2.4 -2.4 L10 0 L2.4 2.4 L0 10 L-2.4 2.4 L-10 0 L-2.4 -2.4 Z"`;
const W = 150, H = 241; // Whiz drawn size (mark aspect 300x482)

/** path: [t, x, y, scale?, rotation?] for Whiz's centre; events: { wave:[t], tap:[[t,x,y]], cheer:[t] } */
const overlays = [
  { id: "w-hello", path: [[0, 2050, 700, 0.6, -20], [0.9, 1640, 560, 1.15, 6], [1.6, 1700, 620, 1, 0], [3.4, 1720, 640, 1, 0]], wave: [1.1, 1.9], sparkle: [[0.9, 1640, 560]] },
  { id: "w-click", path: [[0, 1720, 640, 1, 0], [1.2, 1300, 420, 1.05, -8], [2.6, 880, 300, 1, -4], [3.2, 870, 300, 1, 0]], tap: [[3.0, 790, 341]] },
  { id: "w-study", path: [[0, -160, 760, 0.7, 20], [1.4, 520, 560, 1.1, -6], [3.8, 1120, 360, 1, -3], [4.8, 1130, 360, 1, 0]], wave: [1.6], tap: [[4.4, 1044, 432]] },
  { id: "w-cheer", path: [[0, 2060, 300, 0.7, -15], [0.9, 1700, 260, 1, 0], [7.2, 1710, 270, 1, 0], [9.0, 1720, 280, 1, 0]], bob: [1.0, 6.8], cheer: [7.4] },
];

function comp(o) {
  const dur = o.path[o.path.length - 1][0];
  const [t0, x0, y0, s0 = 1, r0 = 0] = o.path[0];
  const tw = [`tl.set("#${o.id}-whiz", { x: ${x0 - W / 2}, y: ${y0 - H / 2}, scale: ${s0}, rotation: ${r0} }, 0);`, `tl.to("#${o.id}-whiz", { opacity: 1, duration: 0.25 }, ${t0});`];
  for (let i = 1; i < o.path.length; i++) {
    const [a] = o.path[i - 1];
    const [b, x, y, s = 1, r = 0] = o.path[i];
    tw.push(`tl.to("#${o.id}-whiz", { x: ${x - W / 2}, y: ${y - H / 2}, scale: ${s}, rotation: ${r}, duration: ${(b - a).toFixed(2)}, ease: "sine.inOut" }, ${a});`);
  }
  for (const t of o.wave ?? []) tw.push(`tl.fromTo("#${o.id}-bob", { rotation: 0 }, { rotation: 12, duration: 0.16, yoyo: true, repeat: 3, ease: "sine.inOut" }, ${t});`);
  for (const [a, b] of o.bob ? [o.bob] : []) tw.push(`tl.fromTo("#${o.id}-bob", { y: 0 }, { y: -14, duration: 0.55, yoyo: true, repeat: ${Math.max(1, Math.floor((b - a) / 0.55))}, ease: "sine.inOut" }, ${a});`);
  const bursts = [...(o.tap ?? []).map(([t, x, y]) => ({ t, x, y, tap: true })), ...(o.sparkle ?? []).map(([t, x, y]) => ({ t, x, y })), ...(o.cheer ?? []).map((t) => ({ t, x: o.path[o.path.length - 1][1], y: o.path[o.path.length - 1][2] - 60, cheer: true }))];
  const stars = [];
  bursts.forEach((b, k) => {
    if (b.tap) {
      tw.push(`tl.fromTo("#${o.id}-bob", { rotation: 0 }, { rotation: -18, duration: 0.12, yoyo: true, repeat: 1, ease: "power2.out" }, ${(b.t - 0.12).toFixed(2)});`);
      tw.push(`tl.fromTo("#${o.id}-ring${k}", { scale: 0.2, opacity: 0.95 }, { scale: 2.6, opacity: 0, duration: 0.6, ease: "expo.out" }, ${b.t});`);
    }
    if (b.cheer) tw.push(`tl.fromTo("#${o.id}-bob", { y: 0 }, { y: -60, duration: 0.25, yoyo: true, repeat: 1, ease: "power2.out" }, ${b.t});`);
    const n = b.tap ? 8 : 10;
    for (let i = 0; i < n; i++) {
      const a = (i / n) * Math.PI * 2 + k;
      const d = b.tap ? 120 : 190;
      const sid = `${o.id}-st${k}-${i}`;
      stars.push(`<svg id="${sid}" class="w-star" style="left:${b.x - 13}px;top:${b.y - 13}px" viewBox="-10 -10 20 20">${STAR} fill="${i % 2 ? "#ffffff" : "#f7c440"}" /></svg>`);
      tw.push(`tl.fromTo("#${sid}", { x: 0, y: 0, scale: 0, opacity: 1 }, { x: ${Math.round(Math.cos(a) * d)}, y: ${Math.round(Math.sin(a) * d * 0.85)}, scale: ${b.tap ? 1.1 : 1.4}, rotation: 120, duration: 0.7, ease: "expo.out" }, ${b.t});`);
      tw.push(`tl.to("#${sid}", { opacity: 0, duration: 0.3 }, ${(b.t + 0.55).toFixed(2)});`);
    }
    if (b.tap) stars.push(`<div id="${o.id}-ring${k}" class="w-ring" style="left:${b.x - 40}px;top:${b.y - 40}px"></div>`);
  });
  return `<!doctype html>
<!-- Generated by tools/whiz.mjs. Do not edit by hand. -->
<html><head><meta charset="UTF-8" /></head><body>
  <template>
    <style>
      #${o.id}-root { position: absolute; inset: 0; overflow: hidden; pointer-events: none; }
      #${o.id}-whiz { position: absolute; left: 0; top: 0; width: ${W}px; height: ${H}px; transform-origin: 50% 85%; opacity: 0; }
      #${o.id}-bob { position: absolute; inset: 0; transform-origin: 50% 85%; }
      #${o.id}-whiz img { width: 100%; height: 100%; filter: drop-shadow(0 10px 18px rgba(26, 13, 11, 0.45)) drop-shadow(0 0 22px rgba(247, 196, 64, 0.55)); }
      #${o.id}-root .w-star { position: absolute; width: 26px; height: 26px; opacity: 0; }
      #${o.id}-root .w-ring { position: absolute; width: 80px; height: 80px; border-radius: 50%; border: 5px solid #f7c440; box-shadow: 0 0 24px #f7c440; opacity: 0; }
    </style>
    <div id="${o.id}-root" data-composition-id="${o.id}" data-width="1920" data-height="1080">
      ${stars.join("\n      ")}
      <div id="${o.id}-whiz"><div id="${o.id}-bob"><img src="assets/brand/mark-color.svg" alt="" /></div></div>
    </div>
    <script>
      (() => {
        const tl = gsap.timeline({ paused: true });
        ${tw.join("\n        ")}
        tl.to("#${o.id}-root", { opacity: 1, duration: 0.01 }, ${dur});
        window.__timelines["${o.id}"] = tl;
      })();
    </script>
  </template>
</body></html>
`;
}
for (const o of overlays) writeFileSync(join(root, "compositions", `${o.id}.html`), comp(o));
console.log(`whiz overlays: ${overlays.map((o) => o.id).join(", ")}`);
