import React from "react";
/** Magic UI glyphs use Hugeicons' MIT licensed free Stroke Rounded family.
 * Names are semantic roles shared across desktop and the marketing site.
 * Provider brand marks remain separate assets. */
import { HugeiconsIcon, type HugeiconsIconProps } from '@hugeicons/react';
import {
  Alert01FreeIcons,
  AlertCircleFreeIcons,
  ArrowLeft01FreeIcons,
  ArrowRight01FreeIcons,
  ArrowUp01FreeIcons,
  BellFreeIcons,
  BookOpen01FreeIcons,
  Calendar03FreeIcons,
  CalendarCheck01FreeIcons,
  Cancel01FreeIcons,
  CheckFreeIcons,
  ChevronDownFreeIcons,
  ChevronLeftFreeIcons,
  ChevronRightFreeIcons,
  Clock01FreeIcons,
  Database01FreeIcons,
  ExternalLinkFreeIcons,
  File02FreeIcons,
  FileSpreadsheetFreeIcons,
  FileTextFreeIcons,
  FileUploadFreeIcons,
  GitBranchFreeIcons,
  GlobeFreeIcons,
  GridViewFreeIcons,
  Home01FreeIcons,
  InformationCircleFreeIcons,
  ListViewFreeIcons,
  LockFreeIcons,
  Login01FreeIcons,
  Message01FreeIcons,
  Mic01FreeIcons,
  PanelLeftFreeIcons,
  PencilEdit01FreeIcons,
  PlugFreeIcons,
  Presentation01FreeIcons,
  RefreshCwFreeIcons,
  School01FreeIcons,
  ShieldCheckFreeIcons,
  LayersFreeIcons,
  ArrowUpRight01FreeIcons,
  Search01FreeIcons,
  StopFreeIcons,
  TerminalFreeIcons,
  UserFreeIcons
} from '@hugeicons/core-free-icons';

const glyphs = {
  'home': Home01FreeIcons,
  'book': BookOpen01FreeIcons,
  'calendar': Calendar03FreeIcons,
  'panel': PanelLeftFreeIcons,
  'back': ArrowLeft01FreeIcons,
  'forward': ArrowRight01FreeIcons,
  'compose': PencilEdit01FreeIcons,
  'chevron': ChevronRightFreeIcons,
  'chevronDown': ChevronDownFreeIcons,
  'chevronLeft': ChevronLeftFreeIcons,
  'external': ExternalLinkFreeIcons,
  'settings': Database01FreeIcons,
  'school': FileTextFreeIcons,
  'user': UserFreeIcons,
  'grid': GridViewFreeIcons,
  'list': ListViewFreeIcons,
  'lecture': Presentation01FreeIcons,
  'prep': BookOpen01FreeIcons,
  'assignment': FileTextFreeIcons,
  'exam': CalendarCheck01FreeIcons,
  'check': CheckFreeIcons,
  'refresh': RefreshCwFreeIcons,
  'search': Search01FreeIcons,
  'alert': AlertCircleFreeIcons,
  'alertTriangle': Alert01FreeIcons,
  'clock': Clock01FreeIcons,
  'lock': LockFreeIcons,
  'unplug': PlugFreeIcons,
  'globe': GlobeFreeIcons,
  'file': File02FreeIcons,
  'file-text': FileTextFreeIcons,
  'file-spreadsheet': FileSpreadsheetFreeIcons,
  'presentation': Presentation01FreeIcons,
  'git-branch': GitBranchFreeIcons,
  'message': Message01FreeIcons,
  'mic': Mic01FreeIcons,
  'stop': StopFreeIcons,
  'send': ArrowUp01FreeIcons,
  'bell': BellFreeIcons,
  'signin': Login01FreeIcons,
  'terminal': TerminalFreeIcons,
  'info': InformationCircleFreeIcons,
  'x': Cancel01FreeIcons,
  'close': Cancel01FreeIcons,
  'retry': RefreshCwFreeIcons,
  'outlook': Calendar03FreeIcons,
  'myuw': School01FreeIcons,
  'upload': FileUploadFreeIcons,
  'privacy': ShieldCheckFreeIcons,
  'sources': LayersFreeIcons,
  'upRight': ArrowUpRight01FreeIcons,
} as const;

export type MagicGlyphName = keyof typeof glyphs;
export function MagicGlyph({ name, size = 18, className, ...props }: { name: MagicGlyphName; size?: number; className?: string } & Omit<HugeiconsIconProps, 'icon' | 'size'>) {
  return <HugeiconsIcon icon={glyphs[name]} size={size} strokeWidth={1.35} color="currentColor" aria-hidden="true" focusable="false" className={className} {...props} />;
}
